# Generated by Django 6.0.5 on 2026-05-28 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я клієнта")),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Оренда'), ('salary', 'Зарплати'), ('ads', 'Реклама'), ('utilities', 'Комунальні'), ('repair', 'Ремонт'), ('equipment', 'Обладнання'), ('other', 'Інше')], max_length=50, verbose_name='Категорія')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я тренера")),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('telegram_id', models.CharField(blank=True, max_length=100, verbose_name='Telegram ID')),
                ('personal_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Відсоток персональних')),
                ('membership_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Відсоток абонементів')),
                ('split_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Відсоток спліт тренувань')),
                ('single_percent', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Відсоток разових')),
                ('ubd_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Відсоток УБД')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_type', models.CharField(choices=[('trainer_to_gym', 'Тренер здав гроші залу'), ('gym_to_trainer', 'Зал виплатив тренеру')], max_length=30, verbose_name='Тип розрахунку')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer', verbose_name='Тренер')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Абонемент на місяць', max_length=255, verbose_name='Назва абонемента')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('start_date', models.DateField(verbose_name='Дата старту')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('expired', 'Закінчився')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.client', verbose_name='Клієнт')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer', verbose_name='Тренер')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.trainer', verbose_name='Тренер'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('membership', 'Абонемент'), ('personal', 'Персональне тренування'), ('split', 'Спліт тренування'), ('single', 'Разове заняття'), ('ubd_membership', 'Абонемент УБД')], max_length=30, verbose_name='Тип')),
                ('payment_type', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Карта')], max_length=20, verbose_name='Оплата')),
                ('money_location', models.CharField(choices=[('trainer', 'У тренера'), ('gym_card', 'На карті залу')], default='trainer', max_length=30, verbose_name='Де зараз кошти')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.client', verbose_name='Клієнт')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer', verbose_name='Тренер')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва групи')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Опис / вік')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer', verbose_name='Тренер')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата старту')),
                ('end_date', models.DateField(verbose_name='Дата завершення')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('money_location', models.CharField(choices=[('trainer', 'У тренера'), ('gym_card', 'На карті залу')], default='trainer', max_length=30, verbose_name='Де кошти')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Нагадування відправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.client', verbose_name='Клієнт')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer', verbose_name='Тренер')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.traininggroup', verbose_name='Група')),
            ],
        ),
    ]
